---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/gestionlabs/public_html
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R tests $DEPLOYPATH
    - /bin/cp -R writable $DEPLOYPATH
    - /bin/cp * $DEPLOYPATH